env:
  global:
    - TRAVIS_CLONE_DEPTH=1 
    - BUILD_HOSTNAME="travis-ci.org"

jobs:
  include:
    - name: Test
      skip: $TRAVIS_BRANCH == 'main'
      only_if: $TRAVIS_REPO_OWNER == 'shamanthkn5'
      timeout_in: 2m
      persistent_worker:
        labels:
          name: AX61-2
        isolation:
          container:
            image: apon77/aosp:cirrus
            cpu: 2
            memory: 4G
      env_script: env
      show_script: cat $TRAVIS_WORKING_DIR/build_rom.sh
      notify_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/notify.sh | bash
      test_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/test.sh | bash

    - name: Build
      skip: $TRAVIS_BRANCH == 'main'
      only_if: $TRAVIS_REPO_OWNER == 'shamanthkn5'
      depends_on: Test
      timeout_in: 4h
      persistent_worker:
        labels:
          name: AX61-1
        isolation:
          container:
            image: apon77/aosp:cirrus
            cpu: 24
            memory: 120G
            volumes:
              - /home/travis/roms:/home/travis/roms
              - /home/travis/ccache:/home/travis/ccache
              - /home/travis/.config:/home/travis/.config
      show_script: cat $TRAVIS_WORKING_DIR/build_rom.sh
      test_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/test.sh | bash
      sync_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/sync.sh | bash
      tsync_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/tsync.sh | bash
      build_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/build.sh | bash
      ccache_stats_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/ccache_stats.sh | bash
      upload_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/upload.sh | bash
      remove_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/remove.sh | bash

    - name: Post Build
      skip: $TRAVIS_BRANCH == 'main'
      only_if: $TRAVIS_REPO_OWNER == 'shamanthkn5'
      skip_notifications: true
      depends_on: Build
      timeout_in: 2m
      persistent_worker:
        labels:
          name: AX61-2
        isolation:
          container:
            image: apon77/aosp:cirrus
            cpu: 2
            memory: 4G
      test_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/test.sh | bash
      post_build_script: curl -s https://raw.githubusercontent.com/shamanthkn5/temp/main/ci/post_build.sh | bash
      